### ISSUE TITLE
我上传了一个小tips，希望通过

### ISSUE THREAD

**Issue by phychi** [HITSZ-OpenAuto/AUTO3016#1]
我上传了一个小tips，希望通过。话说这个项目文件夹要修改，没有考试也没有其他什么内容。
没啥用的实验抄实验报告完全没问题，是节约时间。但是这个课程设计性质与其他实验有些不同，对我们的能力还是有一定帮助的，可以探讨下能上传什么，既能节约不必要时间，又能对大家有锻炼。

**Comment by longlin10086** [comment]
可以直接在pr下评论，不用另开issue

**Comment by phychi** [comment]
所以我也PR了
